name: Deploy to Amazon EKS

on:
  push:
    branches:
      - master  # Adjust branch name as needed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::123456789012:role/myAmazonEKSClusterRole
          aws-region: eu-north-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 339712876338.dkr.ecr.eu-north-1.amazonaws.com/amithecrprivate

        run: |
          docker build -t $ECR_REGISTRY/dinujayacarsaleapi:latest .
          docker push $ECR_REGISTRY/dinujayacarsaleapi:latest

      - name: Update Kubernetes Deployment
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 --decode > $HOME/.kube/config
          kubectl --kubeconfig=$HOME/.kube/config apply -f deploy.yaml
