name: Deploy to Amazon EKS

on:
  push:
    branches:
      - master  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 339712876338.dkr.ecr.$AWS_REGION.amazonaws.com/amithecrprivate

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 339712876338.dkr.ecr.eu-north-1.amazonaws.com/amithecrprivate
        run: |
          docker build -t $ECR_REGISTRY/dinujayacarsaleapi:latest .
          docker push $ECR_REGISTRY/dinujayacarsaleapi:latest

      - name: Update Kubernetes Deployment
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 --decode > $HOME/.kube/config
          kubectl --kubeconfig=$HOME/.kube/config apply -f springboot-app-deployment.yaml
